### ISSUE TITLE
check

### ISSUE THREAD

**Issue by Miguelramirezjr** [Miguelramirezjr/4.1-git-exercises#1]
## Tasks
- **Getting Started**
  - [x] Follow the assignment instructions to create a new issue.
  - [x] Go through [Learn Git Branching](http://pcottle.github.io/learnGitBranching/) through "Moving Work Around".
- **Git**
  - [x] Fork repository `learn-git-branching` from the class organization page. You will be using the 6 commits in the `master` branch to complete the exercises.
  - Using `git branch`, `git rebase`, etc., make the following changes to your fork of the assignment repository.
    - [x] Create a branch called `exercise-1`. The contents of the branch should be `index.html` with only the boilerplate code and the heading.
    - [x] Create a branch called `exercise-2`. The contents of the branch should be `index.html` with only the boilerplate code and the anchor tag.
    - [x] Create a branch called `exercise-3`. The contents of the branch should be `index.html` with all of the content from `master`, as well as a `<h2>` with your name below the `<h1>`. The commit containing your name should appear in history immediately after the commit adding the `<h1>`.
    - [ ] Create a branch called `exercise-4`. The contents of the branch should be `index.html` with all of the content from `master`, except the paragraph of text should be removed from the page without being removed from the branch's history.
    - [ ] Publish your `exercise-3` to GitHub Pages.

**Comment by Miguelramirezjr** [comment]
Dificulty level -3 
I could not figure out how to remove the <p> from question 4 like how it was described.
Also kept getting an error message when trying to push to gh-pages.
